// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ModuleCard: typeof import('./src/components/ModuleCard/index.vue')['default']
    MusicCard: typeof import('./src/components/MusicCard/index.vue')['default']
  }
}

export { }
